language: erlang
otp_release:
  - 20.0
  - 19.3

services:
  - postgresql

before_script:
  - psql -c 'create database holiday_ping;' -U postgres
  - psql -U postgres -d holiday_ping -a -f ./priv/sql/tables.sql

script:
  - make test
