version: '3.1'

services:

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      # Use postgres/example user/password credentials
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    ports:
      - 8080:8080
